version: '3.3'

volumes:
  static_volume:
  postgres_data:
  media_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
#    build: .
    image: romulinn2575/foodgram_project:latest
    container_name: foodgram
    restart: always
    volumes:
      - ./static_volume:/code/static/
      - ./media_volume:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    container_name: webserver
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static_volume:/code/static
      - ./media_volume:/code/media
