# Generated by Django 3.1.4 on 2021-04-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210418_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipe_ingredients', through='recipes.Ingredient', to='recipes.Product'),
        ),
    ]
