# Generated by Django 3.1.4 on 2021-06-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210421_2031'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='favorite',
            managers=[
            ],
        ),
    ]
