# Generated by Django 3.1.4 on 2021-06-09 12:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210609_1509'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='favorite',
            managers=[
                ('favorite', django.db.models.manager.Manager()),
            ],
        ),
    ]
